### ISSUE TITLE
Add email webhook provider documentation

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/docs#110]

**Comment by ShatilKhan** [comment]
Would like to work on this issue. Please assign & provide some more info

**Comment by ayan-joshi** [comment]
Hello sir please assign me this issue @jainpawan21

**Comment by unicodeveloper** [comment]
@ShatilKhan assigning you to this. 

More context on this. 

- Sign up to the [Novu dashboard](https://web.novu.co/integration). 
- In the [Integrations store](https://web.novu.co/integrations), you can add an email webhook provider.
- So we need a documentation page to show people how to follow the steps required to add the provider, the details needed to be filled, and how to make it active as a provider. Similar documentation is [SES](https://docs.novu.co/channels-and-providers/email/amazonses), [Mailersend](https://docs.novu.co/channels-and-providers/email/mailersend), and [Plunk](https://docs.novu.co/channels-and-providers/email/plunk)
