### ISSUE TITLE
add BurstSms sms provider documentation

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/docs#113]

**Comment by Akhilbisht798** [comment]
Hey, I would like to work on this.
Can you please provide some refrence to this issue.

**Comment by snehpr966** [comment]
Interested to contribute

**Comment by unicodeveloper** [comment]
@Akhilbisht798 assigned to you.

**Comment by unicodeveloper** [comment]
@Akhilbisht798 Please what's the update here? If there's no PR for this by tomorrow, I'll reassign to another person.

**Comment by harshit-senpai** [comment]
> @Akhilbisht798 Please what's the update here? If there's no PR for this by tomorrow, I'll reassign to another person.

Hey I would like to work on this

**Comment by Rutam21** [comment]
@unicodeveloper I would take this up. Thanks.

**Comment by unicodeveloper** [comment]
Assigining this to you @harshit-senpai

**Comment by djangbahevans** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by unicodeveloper** [comment]
Assigned to you now @harshit-senpai ⭐

**Comment by harshit-senpai** [comment]
> Assigned to you now @harshit-senpai ⭐ 

Thanks I will start working on it right away.

**Comment by harshit-senpai** [comment]
@unicodeveloper what are the necessary details that you would like to be added in the Burst-sms Provider's Readme

**Comment by unicodeveloper** [comment]
@harshit-senpai Please check other sms provider documentation in the docs and follow the template.

**Comment by harshit-senpai** [comment]
hey @unicodeveloper i have made the PR, please Review it
