### ISSUE TITLE
Add Kannel sms provider documentation

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/docs#116]

**Comment by Ayaan49** [comment]
Hey, I would like to work on this and if possible could you provide some guidelines?

**Comment by unicodeveloper** [comment]
@Ayaan49 Assigned to you.

More context on this. 

- Sign up to the [Novu dashboard](https://web.novu.co/integration). 
- In the [Integrations store](https://web.novu.co/integrations), you can add an Kannel sms provider.
- So we need a documentation page to show people how to follow the steps required to add the provider, the details needed to be filled, and how to make it active as a provider. Similar documentation is [SES](https://docs.novu.co/channels-and-providers/email/amazonses), [Mailersend](https://docs.novu.co/channels-and-providers/email/mailersend), and [Plunk](https://docs.novu.co/channels-and-providers/email/plunk)

Please let me know if this is clear or not.

**Comment by Ayaan49** [comment]
@unicodeveloper Thanks for the context. I will be working on it soon and let you know if I need any more help! :)

**Comment by Ayaan49** [comment]
Hey @unicodeveloper Since Kannel is an SMS gateway, we will need to configure the SMS provider details to send SMS. So, I wanted to ask, which SMS provider should I use to configure with Kannel?

**Comment by unicodeveloper** [comment]
Hey @Ayaan49 Kannel is the SMS provider. 
![CleanShot 2023-10-09 at 08 28 57](https://github.com/novuhq/docs/assets/2946769/a2595d03-a0dc-43dc-bb72-73919caabfdf)

**Comment by Ayaan49** [comment]
Hey @unicodeveloper, I have created the PR. Please look into it.
