### ISSUE TITLE
Add Maqsam sms provider documentation

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/docs#117]

**Comment by ShatilKhan** [comment]
I'd like to take on this issue, please assign me & if possible provide some info or guidelines

**Comment by unicodeveloper** [comment]
@ShatilKhan assigned to you. 

More context on this. 

- Sign up to the [Novu dashboard](https://web.novu.co/integration). 
- In the [Integrations store](https://web.novu.co/integrations), you can add a maqsam sms provider.
- So we need a documentation page to show people how to follow the steps required to add the provider, the details needed to be filled, and how to make it active as a provider. Similar documentation is [SES](https://docs.novu.co/channels-and-providers/email/amazonses), [Mailersend](https://docs.novu.co/channels-and-providers/email/mailersend), and [Plunk](https://docs.novu.co/channels-and-providers/email/plunk)
