### ISSUE TITLE
Add SmsCentral sms provider documentation

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/docs#118]

**Comment by ShatilKhan** [comment]
Would love to work on this issue
Can you please assign me?
I've done docs contribution for codeacademy before.

**Comment by ayan-joshi** [comment]
@jainpawan21  Please assign me this issue

**Comment by hacanand** [comment]
love to work please assign me this issue

**Comment by unicodeveloper** [comment]
@snehpr966 assigned to you.

**Comment by unicodeveloper** [comment]
@snehpr966 Any updates?

**Comment by unicodeveloper** [comment]
@ShatilKhan Do you want to work on this? I can reassign it to you.

**Comment by ShatilKhan** [comment]
Yeah I sure, I would like to do this one @unicodeveloper 
Please reassign me

**Comment by unicodeveloper** [comment]
I just assigned you @ShatilKhan

**Comment by ShatilKhan** [comment]
PR incoming!

**Comment by snehpr966** [comment]
> @snehpr966 Any updates?

Yeah working on it. Will soon raise a pr

**Comment by ShatilKhan** [comment]
Oh sorry didn't see the update message here
I've just made a PR @unicodeveloper
