### ISSUE TITLE
Issue on docs - Missing API Keys field in API Reference

### ISSUE THREAD

**Issue by mangalnathanvg** [novuhq/docs#133]
Path: /api-reference/

Unable to enter API Keys because of missing field for testing each of these endpoints in the API Reference doc. 
I tried opening the API reference in incognito mode but that did not help.

Screenshot: 
![image](https://github.com/novuhq/docs/assets/16472500/da10fdb7-4ec4-491a-af1a-ea4654f26264)

**Comment by unicodeveloper** [comment]
Thanks for reporting this @mangalnathanvg 

An update from mintlify broke this UI. Looking forward to getting an update from them and fixing this soon

**Comment by unicodeveloper** [comment]
This has been fixed now. You can enter your API key and make a request from the API reference.

![CleanShot 2023-10-04 at 06 40 56](https://github.com/novuhq/docs/assets/2946769/04fe9568-cf44-44a2-950b-508402a1450c)

**Comment by unicodeveloper** [comment]
Closing this issue.
