### ISSUE TITLE
Issue on docs: Wrong Response Body specified in Get-Workflows API Reference

### ISSUE THREAD

**Issue by mayorJAY** [novuhq/docs#143]
Path: /api-reference/workflows/get-workflows

<img width="661" alt="Screenshot 2023-10-02 at 12 05 39" src="https://github.com/novuhq/docs/assets/37001871/9fc93b26-e5fe-456e-9225-1bb92c22abab">

When you click on the dropdown arrow, the response body specified there is not a true representation of what the response body should look like

**Comment by unicodeveloper** [comment]
Something feels off. I'll check this in a couple of hours

**Comment by unicodeveloper** [comment]
Closing this because this is more of an openapi spec issue. This will need to be attended to at a later time.
