### ISSUE TITLE
Icons not visible

### ISSUE THREAD

**Issue by Smartmind12** [novuhq/docs#145]
In the documentation for SDK's icon of ruby and kotlin are not visible as shown in the screenshot.

Kindly assign me this issue to rectify this problem.

![Screenshot 2023-10-02 at 11 06 42 PM](https://github.com/novuhq/docs/assets/91927689/1f80dea3-8f1f-4ab9-80a8-d5d386765758)

**Comment by Cliftonz** [comment]
@Smartmind12 I am good with assigning this one to you. Once you make your PR I will be happy to add you to more.
