### ISSUE TITLE
Improve the UX of Demo page

### ISSUE THREAD

**Issue by Smartmind12** [novuhq/docs#146]
Currently there are only github and demo links in the page which do not look appealing to the user. 
Proposing to use cards and butttons along with icons to improve the UX of the page.

Kindly assign this issue to me so that the improvement can be brought upon!

![Screenshot 2023-10-02 at 11 10 06 PM](https://github.com/novuhq/docs/assets/91927689/69dad381-bbe3-4815-8470-4090432f4b60)

**Comment by unicodeveloper** [comment]
Thanks for the suggestion @Smartmind12. Please help me understand better how you intend to go about this and what the improvement would look like. It's difficult for me to visualize that.

**Comment by Smartmind12** [comment]
> Thanks for the suggestion @Smartmind12. Please help me understand better how you intend to go about this and what the improvement would look like. It's difficult for me to visualize that.
> 
> If it's something I'll like, then I can assign this issue else you'd need to pick from existing issues.

@unicodeveloper Currently the links are just text with embedded links. I wanted to propose that we could use card with icons (Something like the attached screenshot) for the github and try it links to make it look visually better than the exisiting text.
![Screenshot 2023-10-03 at 8 10 55 PM](https://github.com/novuhq/docs/assets/91927689/19bc0471-5b91-4162-a2a2-1e03d979f892)

**Comment by unicodeveloper** [comment]
This is fair. I like the UX improvement. Let's do it. @Smartmind12

**Comment by Smartmind12** [comment]
> This is fair. I like the UX improvement. Let's do it. @Smartmind12

Hey @unicodeveloper I created them locally are these looking good? Any suggestions?
![Screenshot 2023-10-06 at 2 43 04 AM](https://github.com/novuhq/docs/assets/91927689/68bf3693-9a62-4f94-b859-8b49b67cde9f)
![Screenshot 2023-10-06 at 2 43 18 AM](https://github.com/novuhq/docs/assets/91927689/9de419b7-77d4-48d1-bedf-8a6c21e7ae65)

**Comment by Smartmind12** [comment]
Hey @unicodeveloper any updates on this? Is the design good to make the PR?

**Comment by unicodeveloper** [comment]
It looks good. Yes, you can go ahead to make the PR @Smartmind12
