### ISSUE TITLE
Issue on docs: Python logo 

### ISSUE THREAD

**Issue by dev-muyiwa** [novuhq/docs#149]
Path: /sdks/introduction

The Python logo has a red shade to it as opposed to the standard blue and yellow colour.

@unicodeveloper, do assign me to this issue.

**Comment by unicodeveloper** [comment]
@dev-muyiwa We have other logos with that color as well. We are okay with it being like that at the moment. 

Please can you pick from the existing issues or come up with a better issue. Thanks
