### ISSUE TITLE
Adding the missing icons to SDK Navigation Bar

### ISSUE THREAD

**Issue by Smartmind12** [novuhq/docs#154]
Currently icons for the SDK's in the Navigation bar are missing unlike as in the case for quickstart.

Proposed: To add the icons to SDK Navigation bar create uniformity between UX across pages.

Kindly assign this issue to me so that i can add the PR for this!

![Screenshot 2023-10-03 at 8 50 06 PM](https://github.com/novuhq/docs/assets/91927689/3c1ed3c7-2f4f-419a-baa6-f24d9f6a0392) ![Screenshot 2023-10-03 at 8 50 58 PM](https://github.com/novuhq/docs/assets/91927689/82087fcc-0c9c-4c3a-b5ab-cb724d7d96eb)

**Comment by unicodeveloper** [comment]
Yes @Smartmind12 you can work on the issue.

**Comment by unicodeveloper** [comment]
Any updates @Smartmind12

**Comment by Smartmind12** [comment]
Hey @unicodeveloper i was busy at work so will close this by end of today!
