### ISSUE TITLE
Add Curl Request Examples for Events API in API Reference Documentation

### ISSUE THREAD

**Issue by unicodeveloper** [novuhq/docs#163]
At the moment, we have request examples for different technologies, Node.js, PHP, Ruby, Go in the API Reference documentation.

![CleanShot 2023-10-04 at 07 24 58](https://github.com/novuhq/docs/assets/2946769/b3a1d0f3-b62c-4bb9-b521-d0d51cf67993)

Now, we need a request example for `Curl` for the Events API in the API reference documentation

- [Trigger event, ](https://docs.novu.co/api-reference/events/trigger-event)
- [Bulk Trigger event](https://docs.novu.co/api-reference/events/bulk-trigger-event)
- [Broadcast event to all](https://docs.novu.co/api-reference/events/broadcast-event-to-all)
- [Cancel triggered event](https://docs.novu.co/api-reference/events/cancel-triggered-event)

**Comment by Siddharth9890** [comment]
@unicodeveloper can i work on it?

**Comment by fadkeabhi** [comment]
I would like to work on this issue. Can you assign it to me.

**Comment by unicodeveloper** [comment]
@Siddharth9890 I assigned you to another issue. I'll be assigning @fadkeabhi to this.

**Comment by unicodeveloper** [comment]
Assigned @fadkeabhi ⭐

**Comment by unicodeveloper** [comment]
@fadkeabhi Please any updates on this? It's been 4 days. We'll reassign this issue to another person tomorrow if there's no update.
