### ISSUE TITLE
Add Curl Request Examples for Workflow API in API Reference Documentation

### ISSUE THREAD

**Issue by unicodeveloper** [novuhq/docs#164]
At the moment, we have request examples for different technologies, Node.js, PHP, Ruby, Go in the API Reference documentation.

![CleanShot 2023-10-04 at 07 36 39](https://github.com/novuhq/docs/assets/2946769/ea5b05b8-b38e-422a-908f-8c533bffe216)

Now, we need a request example for `Curl` for the Workflow API in the API reference documentation

- [Get workflows](https://docs.novu.co/api-reference/workflows/get-workflows)
- [Create Workflow](https://docs.novu.co/api-reference/workflows/create-workflow)
- [Get Workflow](https://docs.novu.co/api-reference/workflows/get-workflow)
- [Update Workflow](https://docs.novu.co/api-reference/workflows/update-workflow)
- [Delete Workflow](https://docs.novu.co/api-reference/workflows/delete-workflow)
- [Update Workflow Status](https://docs.novu.co/api-reference/workflows/update-workflow-status)

**Comment by Siddharth9890** [comment]
@unicodeveloper can i work on this?

**Comment by fadkeabhi** [comment]
I would like to work on this issue. Can you assign it to me.

**Comment by unicodeveloper** [comment]
Assigned to you @Siddharth9890 🌟
