### ISSUE TITLE
Add Curl Request Examples for Workflow Groups API in API Reference Documentation

### ISSUE THREAD

**Issue by unicodeveloper** [novuhq/docs#165]
At the moment, we have request examples for different technologies, Node.js, PHP, Ruby, Go in the API Reference documentation.

![CleanShot 2023-10-04 at 07 37 10](https://github.com/novuhq/docs/assets/2946769/c1c2ce36-6d5c-4ea2-bfe1-d60d39615854)

Now, we need request examples for `Curl` for the Workflow groups API in the API reference documentation

- [Get workflow groups](https://docs.novu.co/api-reference/workflow-groups/get-workflow-groups)
- [Create workflow group](https://docs.novu.co/api-reference/workflow-groups/create-workflow-group)
- [Get workflow group](https://docs.novu.co/api-reference/workflow-groups/get-workflow-group)
- [Delete workflow group](https://docs.novu.co/api-reference/workflow-groups/delete-workflow-group)
- [Update workflow group](https://docs.novu.co/api-reference/workflow-groups/update-workflow-group)

**Comment by seventh-sense-claims** [comment]
hey @unicodeveloper could you assign this issue to me?

**Comment by ST1LLWATER** [comment]
Can I work on this?

**Comment by aasthaagarwal2003** [comment]
Can I help?

**Comment by unicodeveloper** [comment]
Assigning to you now @seventh-sense-claims

**Comment by unicodeveloper** [comment]
Assigned @seventh-sense-claims 🌟

**Comment by unicodeveloper** [comment]
@seventh-sense-claims Please what's the update here? If by tomorrow, there's no update, I'll have to reassign someone else.

**Comment by FroostyCodes** [comment]
Hi @unicodeveloper I would like to work on this issue if there is no any updates

**Comment by unicodeveloper** [comment]
@aasthaagarwal2003 @ST1LLWATER are any of you still available to work on this?

**Comment by rahul0x00** [comment]
@unicodeveloper 
Hi, I'm up for this issue

**Comment by fadkeabhi** [comment]
Hey, I would like work on this issue.

**Comment by Ajiboso-Adeola** [comment]
Hi, I would love to work on this issue

**Comment by unicodeveloper** [comment]
@rahul0x00 Assigning this issue to you now.

**Comment by unicodeveloper** [comment]
You have been assigned @rahul0x00 🌟

**Comment by nabinbhatt** [comment]
Hello @unicodeveloper as the assignee has not made a PR since 5 days, can you assign this issue to me?

**Comment by nabinbhatt** [comment]
Hello @unicodeveloper please review my PR here: #296
