### ISSUE TITLE
Missing response data in docs. https://docs.novu.co/api-reference/subscribers/handle-chat-oauth

### ISSUE THREAD

**Issue by sarojregmi200** [novuhq/docs#169]
The below mentioned link shows the portion of the docs where the response data is missing.

Issue is also raised here, But I think this repo is the correct place: novuhq/novu#4192
[Docs Link](https://docs.novu.co/api-reference/subscribers/handle-chat-oauth)

P.S : Can I be assigned to solve this issue?

**Comment by unicodeveloper** [comment]
@sarojregmi200 Please what's the update here?

**Comment by sarojregmi200** [comment]
@unicodeveloper, I am extremely sorry for not responding for this long. I was suffering from dengue. And was not able to get out of the bed, for almost a week. I am fine now, and would love to work on the PR, can it be extended by 1-2 days?

Hope you understand.

**Comment by unicodeveloper** [comment]
@sarojregmi200 Any updates here?

**Comment by Rutam21** [comment]
@unicodeveloper I would like to take this up and raise a PR asap. You can assign it to me. Thank you.

**Comment by unicodeveloper** [comment]
@Rutam21 Assigning this to you now

**Comment by unicodeveloper** [comment]
Assigned @Rutam21 🌟

**Comment by utkarsh125** [comment]
Any update on the issue @unicodeveloper ? If not, I would like to take up on the issue...

**Comment by Rutam21** [comment]
I am working on it. In talks with the team to clear something before raising the PR.
