### ISSUE TITLE
Add Curl Request Examples for Execution Details API in API Reference Documentation

### ISSUE THREAD

**Issue by mr-palindrome** [novuhq/docs#170]
At the moment, it has request examples for different technologies, Node.js, PHP, Ruby, Go in the API Reference documentation.
I'd like to add the respective curl request example for Execution Details API as well.

I'll be taking reference from following:

- https://docs.novu.co/api-reference/execution-details/get-execution-details
- https://api.novu.co/api#/Execution%20Details/ExecutionDetailsController_getExecutionDetailsForNotification

**Comment by unicodeveloper** [comment]
Sure. I will assign that to you now.

**Comment by mr-palindrome** [comment]
@unicodeveloper @davidsoderberg @LetItRock
can you please have a look on #179
