### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by fadkeabhi** [novuhq/docs#172]
Path: /api-reference/integrations/get-v1integrationsin-appstatus

As mentioned in https://github.com/novuhq/novu/pull/4406. The endpoint "/v1/integrations/in-app/status" is not public today.  I think there should be an warning or some kind of message saying same. As not having this kind of message may lead to confusion of developers.

I would like to make those changes. Assign it to me. Can you assign it to me.

**Comment by davidsoderberg** [comment]
My changes and some work by @unicodeveloper will remove those endpoints from the api reference that I am guessing you are referring to.
