### ISSUE TITLE
Wrong redirect url in FAQ Section of docs

### ISSUE THREAD

**Issue by utsavbhattarai007** [novuhq/docs#176]
# Problem
![Screenshot from 2023-10-06 11-50-23](https://github.com/novuhq/docs/assets/95236817/96584333-602c-4ed2-9b7d-a7a8ecb981f4)

In the FAQ section, There is a question as "I am missing a channel provider, can I ask for one? Or add it myself?" and In the answer, There is the link to contribute the provider which redirect to wrong URL that is https://docs.novu.co/community/create-provider

# Expected Solution:
Update the wrong URL from https://docs.novu.co/community/create-provider to https://docs.novu.co/community/add-a-new-provider.

Can you assign to me to resolve this issue?

**Comment by unicodeveloper** [comment]
Assigning you now @utsavbhattarai007

**Comment by utsavbhattarai007** [comment]
Thanks @unicodeveloper
