### ISSUE TITLE
Adding the Ruby and Kotlin icon under Start Point page

### ISSUE THREAD

**Issue by Smartmind12** [novuhq/docs#183]
Currently Ruby and Kotlin Icons are not displayed in the Getting started page so need to add the same.

![Screenshot 2023-10-07 at 9 52 22 PM](https://github.com/novuhq/docs/assets/91927689/fa65d07c-9611-43f9-876d-583991734fbc)

**Comment by unicodeveloper** [comment]
Assigned to you now @Smartmind12

**Comment by Smartmind12** [comment]
> Assigned to you now @Smartmind12

Thanks alot @unicodeveloper I have made the PR for this for your review!

**Comment by unicodeveloper** [comment]
Seen @Smartmind12
