### ISSUE TITLE
Improve UX design of the community page

### ISSUE THREAD

**Issue by Smartmind12** [novuhq/docs#185]
Currently the Community Page is text heavy and uses hyper links. 
I propose to beautify it by using cards and icons to represent the same information instead of using hyperlinks.
Kindly assign this issue so as to work on it.

![Screenshot 2023-10-07 at 9 47 22 PM](https://github.com/novuhq/docs/assets/91927689/5e11771c-599a-4eec-924f-bdb93cbdd11b)

**Comment by unicodeveloper** [comment]
Thanks for suggesting this, but it’s not needed in this instance.

Please can you pick other existing issues?

**Comment by Smartmind12** [comment]
> Thanks for suggesting this, but it’s not needed in this instance. Please can you pick other existing issues?
> […](#)

Sure i understand!
