### ISSUE TITLE
Wrong novu's linkedin handle in the docs

### ISSUE THREAD

**Issue by utsavbhattarai007** [novuhq/docs#190]
Problem:

![image](https://github.com/novuhq/docs/assets/95236817/87a21f5b-2e15-4e71-b3cf-e5df529181b3)

In the footer of the docs, There is a wrong linkedin handle which is https://www.linkedin.com/company/novuhq/

Solution:
Changed the wrong handle to correct one which is https://www.linkedin.com/company/novuco/

P.S. Can you assign to me to resolve this issue?

**Comment by unicodeveloper** [comment]
You have been assigned @utsavbhattarai007

**Comment by utsavbhattarai007** [comment]
Thanks @unicodeveloper

**Comment by utsavbhattarai007** [comment]
Hi @unicodeveloper , Is it necessary to have hacktoberfest label for acceptable PR's? 
Is it necessary. Then, Would you put on this issue 😅😅 ?
