### ISSUE TITLE
Add alt-text to images in the Activity page

### ISSUE THREAD

**Issue by EshaanAgg** [novuhq/docs#193]
There are many images and videos on the [Activity page](https://docs.novu.co/activity-feed/introduction) that have no `alt` attribute, which makes the site non-accessible. This needs to be fixed.

**Comment by EshaanAgg** [comment]
I would like to be assigned this issue.

**Comment by unicodeveloper** [comment]
Please can you pick from the list of other issues? We'll like to not attend to this type of issue for now.
