### ISSUE TITLE
Poor contrast in the reading mode toggle switch

### ISSUE THREAD

**Issue by EshaanAgg** [novuhq/docs#195]
Currently, the light mode-dark mode toggle switch has a really poor contrast for the grey background bar, making it almost invisible in the light mode and only visible clearly in the dark mode. 
![image](https://github.com/novuhq/docs/assets/96648934/16aed8ed-dded-4dc6-b3b1-e5417d344557)
![image](https://github.com/novuhq/docs/assets/96648934/d8deb1d3-cdba-42ce-acb6-0807fa2b0759)

**Comment by EshaanAgg** [comment]
I would like to be assigned this issue.

**Comment by unicodeveloper** [comment]
Thanks for raising this. We don't want to change anything here. So we'll like you to pick from other existing issues.
