### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by nitin-1926** [novuhq/docs#197]
Path: /api-reference/events/cancel-triggered-event

According to the doc it says that we can cancel a triggered event (delay etc) using novu.subscribers.cancel("transactionId");

But when I tried to use this it gave the following error: Property 'cancel' does not exist on type 'Subscribers'.

On checking the types of 'Subscribers', I found that there is no such function. I am on version 0.18.0

Please check this and update the doc accordingly if required.

<img width="1440" alt="Screenshot 2023-10-10 at 8 45 57 AM" src="https://github.com/novuhq/docs/assets/44253685/701e47ba-7635-42d0-b0e1-da84a274c5c9">
<img width="1440" alt="Screenshot 2023-10-10 at 8 43 43 AM" src="https://github.com/novuhq/docs/assets/44253685/71b524f2-422d-4fe5-927b-29284e8397e1">

**Comment by Smartmind12** [comment]
@unicodeveloper would you like me to make the update in the documentation for you?

**Comment by nitin-1926** [comment]
@unicodeveloper , thanks for replying. I would like to make this change to the doc if that is feasible to you.
Also can you tell me that if I am triggering 1 event with multiple subscribers, there is only 1 transactionId for it but it shows 3 different events for that in the dashboard. Now if I cancel that transactionId, will all the three events get cancelled?

I am facing a similar issue, debugging it more though!

**Comment by unicodeveloper** [comment]
@nitin-1926 Assigned to you. Please submit a PR to the effect. Yes, if you cancel that transactionId, they should get cancelled.

**Comment by nitin-1926** [comment]
Thanks for assigning it to me.
Also @unicodeveloper , I am using `/v1/events/trigger/{transactionId}` the following DELETE Api to delete but it is only deleting 1 event out of that 3. I will try using the function that you have mentioned.

**Comment by nitin-1926** [comment]
Update, could find it in `await this.novu.events.cancel(transactionId);`
![Screenshot 2023-10-11 at 1 56 32 PM (2)](https://github.com/novuhq/docs/assets/44253685/ce1ff81f-372a-47ab-8ae5-379a57ae30a1)

<img width="1440" alt="Screenshot 2023-10-11 at 1 56 32 PM" src="https://github.com/novuhq/docs/assets/44253685/892155e3-9dbf-4306-bd46-1f8b53581442">

**Comment by unicodeveloper** [comment]
Check the Activity Feed. How many events and transaction Id are you seeing there? You can use that to verify if it's only one transaction id or multiple ids for the different events
