### ISSUE TITLE
Cards missing in the Overview Page

### ISSUE THREAD

**Issue by Smartmind12** [novuhq/docs#203]
Currently there are 15 quickstart pages  for all languages however only 10 cards are present in the Overview page (https://docs.novu.co/quickstarts/01-introduction) linking to the quickstart. Missing Cards and Links are for:
1. Vanilla JS
2. Redwood JS
3. Iframe
4. Node JS
5. Next JS

![Screenshot 2023-10-11 at 8 33 40 AM](https://github.com/novuhq/docs/assets/91927689/fadc2298-a25e-45ee-9a23-a2ab09655b48)

Proposal: Adding the cards and correct links so that user can access thee preferred quickstart directly form the overview page.
Kindly assign this to me so that i can work on it!

**Comment by unicodeveloper** [comment]
Assigned to you @Smartmind12

**Comment by Smartmind12** [comment]
@unicodeveloper which format do i use for the text of the cards? 
1. Connect a Go application to Novu. 
OR
2. Embed a real-time notification center component in your GO application

**Comment by unicodeveloper** [comment]
For Node and Next, use option 1.

For the others, use option 2 @Smartmind12
