### ISSUE TITLE
Inconsistent api response for `Delete Feed` endpoint

### ISSUE THREAD

**Issue by Aunali321** [novuhq/docs#209]
The api endpoint for `Create Feed` returns an object:

```json
{
  "data": {
    "_id": "string",
    "name": "string",
    "identifier": "string",
    "_environmentId": "string",
    "_organizationId": "string"
  }
}
```

but the response of `Delete Feed` returns an array of objects:

```json
{
  "data": [
    {
      "_id": "string",
      "name": "string",
      "identifier": "string",
      "_environmentId": "string",
      "_organizationId": "string"
    }
  ]
}
```

To be consistent,  `Delete Feed` should not return an array or the `Create Feed` should return an array as well.

**Comment by unicodeveloper** [comment]
Is the issue about the documentation of the response or the response itself from the API? @Aunali321

**Comment by unicodeveloper** [comment]
We should update the response to be object for `Create Feed` and confirm from the API to be sure whether the  `Delete Feed` returns an array or an object.

Because we can't change the API response structure to avoid it breaking existing clients that are consuming it. @Aunali321

**Comment by Aunali321** [comment]
Agree with breaking changes part. Maybe it can be fixed in v2 api. For now let's just change the response of create feed. I double checked and can confirm delete feed responds with an array. Also cross checked with swagger/openapi documentation https://api.novu.co/api#/Feeds/FeedsController_deleteFeed

**Comment by Aunali321** [comment]
Made a PR. Please Review
