### ISSUE TITLE
Error in Demo section of docs

### ISSUE THREAD

**Issue by utsavbhattarai007** [novuhq/docs#222]
![Screenshot from 2023-10-12 21-00-47](https://github.com/novuhq/docs/assets/95236817/36ce21cd-099c-47ff-b573-4b505a7527a2)

@unicodeveloper is these the issue or some sort of other type of error?

**Comment by unicodeveloper** [comment]
Someone's recent contribution broke this page. So, yes this is an error @utsavbhattarai007 

Do you wanna fix?

**Comment by utsavbhattarai007** [comment]
Yes, I wanna fix

**Comment by unicodeveloper** [comment]
Please send in a PR.

**Comment by utsavbhattarai007** [comment]
Thanks @unicodeveloper

**Comment by utsavbhattarai007** [comment]
Hi @unicodeveloper , I solved this issue and found the another issue of wrong redirect url of github link of email digest app and solved it

**Comment by unicodeveloper** [comment]
That's amazing! @utsavbhattarai007

**Comment by utsavbhattarai007** [comment]
@unicodeveloper PR done and One last thing Can you label **hacktoberfest** this PR https://github.com/novuhq/docs/pull/212 and above one😅😅

**Comment by utsavbhattarai007** [comment]
Thanks
