### ISSUE TITLE
Need Change Twitter logo to X logo

### ISSUE THREAD

**Issue by pabitra0011** [novuhq/docs#225]
In the footer logo section, the Twitter logo is an old logo that must be changed to the current one.

![image](https://github.com/novuhq/docs/assets/94389910/9c8d213b-b567-47e0-8c51-6434e89617d2)

How to reproduce:-
You can see it in any footer section of any page.

**Comment by unicodeveloper** [comment]
Thanks for the PR. Unfortunately we have decided not to change it yet.
