### ISSUE TITLE
Replacing Readme.md  links with Markdown badges

### ISSUE THREAD

**Issue by shelar1423** [novuhq/docs#237]
- instead of having these we can have markdown badges is my suggestion ? if so then i would like to work on this issue
![image](https://github.com/novuhq/docs/assets/82649533/fed2d87d-2555-4bc5-871f-91ff6f01abf1)

**Comment by shelar1423** [comment]
@unicodeveloper  what say

**Comment by unicodeveloper** [comment]
What do you mean by markdown badges?

**Comment by shelar1423** [comment]
@unicodeveloper something like this 
![image](https://github.com/novuhq/docs/assets/82649533/960db9e8-848c-45bc-927b-a32c2f4b94fa)
![image](https://github.com/novuhq/docs/assets/82649533/668d270e-afff-43ac-b357-54b1ba44819c)

**Comment by unicodeveloper** [comment]
Sorry, we really don’t need that at this time.

**Comment by shelar1423** [comment]
@unicodeveloper sure,also can you review my other 2 PR's and give your suggestions on them too?so that i can fix it acc to your suggestions
