### ISSUE TITLE
Missing 'Slack' identifier

### ISSUE THREAD

**Issue by sumitsaurabh927** [novuhq/docs#238]
In the 'Chat' section, for manually managed section, we've the following to be used in Node:
```
import { Novu, ChatProviderIdEnum } from '@novu/node';

const novu = new Novu("<NOVU_API_KEY>");

const body = req.body; // From your HTTPS listener
await novu.subscribers.setCredentials('subscriberId', ChatProviderIdEnum., {
webhookUrl: body.incoming_webhook.url,
});
```

In the 4th line, instead of `ChatProviderIdEnum.`, it should be `ChatProviderIdEnum.Slack,{...}`

So, we're missing `Slack` from it!

Attached is a screenshot for reference:
<img width="1492" alt="SCR-20231014-umuj" src="https://github.com/novuhq/docs/assets/62152915/942a525a-50e6-432d-9960-921c162d991f">

**Comment by sumitsaurabh927** [comment]
@FrancescoXX you'd asked to work on it, are you still interested?

**Comment by jude-san** [comment]
Hi @sumitsaurabh927  I want to work on it.

**Comment by sumitsaurabh927** [comment]
@jude-san the previous person had asked me to assign it to him.

Let's wait for his response, if he's not interested, I'll assign it to you!

**Comment by jude-san** [comment]
@sumitsaurabh927 noted

**Comment by devshah7774** [comment]
@sumitsaurabh927 , please review my above PR. Apologies for not asking before creating a PR. It was because I was not sure as it is my first PR.
