### ISSUE TITLE
Updating new icons with better brand look and colors

### ISSUE THREAD

**Issue by shelar1423** [novuhq/docs#242]
when i was replacing the icons for the site, i found a website which can give the proper  icons in svg code format, like icon with proper brand guidlines , so i feel we can replace majority if the icons of programming languages with it as i did with kotlin and ruby instead of using plain single color icons .

i.e python has multiple colors for its logo but at current state of the site we dont have accessibility to do give icon multiple colors .
![image](https://github.com/novuhq/docs/assets/82649533/6b41dd34-52ea-4aff-9629-82b0f4eae354)

Where as python should be like this :
![image](https://github.com/novuhq/docs/assets/82649533/221aa3e0-60ab-4799-9e24-1db466bc1091)

###  I would like to work on this issue

**Comment by unicodeveloper** [comment]
What pages of the docs are you hoping to make these changes.

We have the Quickstarts overview page, and we also have the SDK overview page. Is this going to apply on both ends? @shelar1423

**Comment by unicodeveloper** [comment]
Alright, that's good. Assigning to you now

**Comment by unicodeveloper** [comment]
Assigned to you now @shelar1423

**Comment by shelar1423** [comment]
sure, thanks @unicodeveloper

**Comment by shelar1423** [comment]
Hey I was wondering do I make a single pr for all the pages ? Will it be confusing or is it fine ? @unicodeveloper

**Comment by shelar1423** [comment]
can i create a pr for each page ? @unicodeveloper  so that itll be better to refer  ?

**Comment by shelar1423** [comment]
sure @unicodeveloper
