### ISSUE TITLE
ICONS MISSING IN SIDE BAR

### ISSUE THREAD

**Issue by shelar1423** [novuhq/docs#246]
is something planned for this  ? or shall i find out the solution for these empty icons
![image](https://github.com/novuhq/docs/assets/82649533/fc20b9f3-ad8a-4fe5-8637-5cd0c2529a0e)

**Comment by shelar1423** [comment]
@unicodeveloper

**Comment by unicodeveloper** [comment]
If you can find a solution, please go ahead. @shelar1423
