### ISSUE TITLE
link broken in Faq section

### ISSUE THREAD

**Issue by shelar1423** [novuhq/docs#250]
![image](https://github.com/novuhq/docs/assets/82649533/33585d72-4973-44f8-97d2-78e8312cf04d)
![image](https://github.com/novuhq/docs/assets/82649533/4cea692e-5cf3-490a-be01-f9ecbb60ff50)

**Comment by shelar1423** [comment]
@unicodeveloper is this the link which should be shown ?
![image](https://github.com/novuhq/docs/assets/82649533/6ad58724-540a-470c-8cfc-c19e12868e38)

**Comment by sumitsaurabh927** [comment]
Yes

**Comment by sumitsaurabh927** [comment]
Do you wanna work on this @shelar1423 ?

**Comment by shelar1423** [comment]
@sumitsaurabh927 yes
