### ISSUE TITLE
Not all images source from /images

### ISSUE THREAD

**Issue by biplobsd** [novuhq/docs#260]
Some of images source not from `/images`

![image](https://github.com/novuhq/docs/assets/43641536/2d8e0c0c-d37d-40d9-984e-2f99bf85c892)

If #247 merged then those markdown image tag should be html img tag.
![image](https://github.com/novuhq/docs/assets/43641536/6a2c0831-15dc-44ed-8627-9dc6c3af0c97)

**Comment by biplobsd** [comment]
@sumitsaurabh927 Could you assign to me?

**Comment by unicodeveloper** [comment]
Thanks for this, but not all the images need to be from the `/images` directory. They can either be from cloudinary or from the local directory. I'll close this issue now.
