### ISSUE TITLE
Add info about feature flag

### ISSUE THREAD

**Issue by michaldziuba03** [novuhq/docs#261]
It's confusing for some contributors and maybe some users who deploy Novu - "why novu looks different on self-hosted version".

I think it's good to mention about flags in docs.

**Comment by unicodeveloper** [comment]
@michaldziuba03 Please can add more meat to the description of this issue? Novu only looks a bit different based on a few features that need to be activated or not via the feature flags.

So it will be nice to mention some of them that you are aware of so that someone can pick this up

**Comment by michaldziuba03** [comment]
@unicodeveloper 

They are listed on `.env` file in web app codebase:

```sh
IS_TEMPLATE_STORE_ENABLED=  IS_MULTI_PROVIDER_CONFIGURATION_ENABLED= 
 IS_MULTI_TENANCY_ENABLED=
```

But the thing is it should be mentioned in docs as well. It will be easier to send links to the people on Discord who are confused.

It can be mentioned in the section where all env variables are listed. So most people who will want to run Novu on local machine will be aware.

https://docs.novu.co/community/run-in-local-machine#set-up-your-environment-variables

You can assign me to handle that.

**Comment by unicodeveloper** [comment]
Assigning you then @michaldziuba03

**Comment by unicodeveloper** [comment]
You have been assigned @michaldziuba03 🌟

**Comment by toddb** [comment]
> They are listed on `.env` file in web app codebase

https://github.com/novuhq/novu/blob/next/apps/web/.env

**Comment by toddb** [comment]
@michaldziuba03 can I note if you are updating the documentation and environment file that `LOGGING_LEVEL` is also a valid undocumented variable—

 LOGGING_LEVEL: [warn|info|error]
 
 Note: it is in some .env files (eg [here](https://github.com/novuhq/novu/blob/next/apps/api/src/.env.development))
