### ISSUE TITLE
Add Python `Regenerate api keys` Examples for Environments API in API Reference Documentation

### ISSUE THREAD

**Issue by biplobsd** [novuhq/docs#262]
Page: https://docs.novu.co/api-reference/environments/regenerate-api-keys

My example:
![image](https://github.com/novuhq/docs/assets/43641536/c6eb4b58-4254-4a38-be55-6ceadd4fdca1)

**Comment by biplobsd** [comment]
@unicodeveloper I like to work on this

**Comment by biplobsd** [comment]
https://github.com/novuhq/novu-python/pull/99

**Comment by unicodeveloper** [comment]
This example means you will add the appropriate Python regenerate_api_keys method  @biplobsd

**Comment by unicodeveloper** [comment]
Assigning to you now @biplobsd
