### ISSUE TITLE
Add Python `Get api keys Examples` for Environments API in API Reference Documentation

### ISSUE THREAD

**Issue by biplobsd** [novuhq/docs#263]
Page: https://docs.novu.co/api-reference/environments/get-api-keys

My example: 
![image](https://github.com/novuhq/docs/assets/43641536/737ddb2a-bc3e-40d4-bb62-45e42fc26564)

**Comment by biplobsd** [comment]
@unicodeveloper I like to work on this issue

**Comment by unicodeveloper** [comment]
@biplobsd I don't think you should be creating them on different issues. You should batch them into one issue. All of these relate to the Environments API, so everything about the environments API should be one issue.

**Comment by unicodeveloper** [comment]
If you want another issue, then it has to be something in another API.

**Comment by biplobsd** [comment]
> @biplobsd I don't think you should be creating them on different issues. You should batch them into one issue. All of these relate to the Environments API, so everything about the environments API should be one issue.

Okay.
