### ISSUE TITLE
Add cURL `Get current environment`, `Get environments`, `Get api keys`, `Regenerate api keys` Examples for Environments API in API Reference Documentation

### ISSUE THREAD

**Issue by biplobsd** [novuhq/docs#265]
Page: https://docs.novu.co/api-reference/environments/get-current-environment

## Get current environment
![image](https://github.com/novuhq/docs/assets/43641536/a91b6470-ed2b-491b-bdc6-940f2ece5215)

## Get environments
![image](https://github.com/novuhq/docs/assets/43641536/e2362e30-3bfc-4ec0-a702-b02ff20762c2)

## Get api keys
![image](https://github.com/novuhq/docs/assets/43641536/c29f5e14-f7f7-4bd8-ad7b-d6715b51a8c3)

## Regenerate api keys
![image](https://github.com/novuhq/docs/assets/43641536/7f2b33a1-3b80-4b28-b8a5-7e68a400194f)

**Comment by biplobsd** [comment]
@unicodeveloper I like to work on this

**Comment by jainpawan21** [comment]
@biplobsd 

Sorry for delayed response.

let me know if you still want to work on this
