### ISSUE TITLE
Add cURL Examples for NotificationApi in API Reference Documentation

### ISSUE THREAD

**Issue by nabinbhatt** [novuhq/docs#277]
Link to the page in docs: https://docs.novu.co/api-reference/notification/get-notifications

the current examples are auto-generated. ref: https://github.com/novuhq/docs/pull/269

**Comment by harshit-senpai** [comment]
Hey @nabinbhatt can I work on this

**Comment by nabinbhatt** [comment]
@unicodeveloper I would like to work on this, have a review and let me know

**Comment by nabinbhatt** [comment]
@jainpawan21 please assign me
