### ISSUE TITLE
Inconsistency in Font Size and Text Color: Quickstart Documentation's Conclusion

### ISSUE THREAD

**Issue by sshiwangi** [novuhq/docs#280]
The client-side quickstart documentation exhibits an issue where, upon clicking, the conclusion section in the content guide on the right side fails to adjust the font size and text color as seen in the other sections in the desktop view. This inconsistency in styling impacts the visual coherence of the documentation.

Here's a video of how it is behaving currently.
https://github.com/novuhq/docs/assets/77545230/56d43e29-ea70-49ff-b339-69c814fc1438

Screenshots
All of the sections are working fine except the conclusions section.
![Screenshot 2023-10-21 144653](https://github.com/novuhq/docs/assets/77545230/626c57f2-2b7b-4257-9340-684f3ae2145d)
![Screenshot 2023-10-21 1432591](https://github.com/novuhq/docs/assets/77545230/973bbde6-6638-45d6-8e24-0057231ba4cb)

@unicodeveloper I would like to fix this issue. Can I work on this?

**Comment by jainpawan21** [comment]
Hi @sshiwangi 

Thanks for your interest in contribution. I see this is not happening now.
