### ISSUE TITLE
Add mailtrap sms provider documentation

### ISSUE THREAD

**Issue by Ayaan49** [novuhq/docs#283]
There isn't a Mailtrap documentation to show people how to follow the steps required to add the provider, the details needed to be filled, and how to make it active as a provider. Can I work on it if it's okay to do so?

**Comment by unicodeveloper** [comment]
There’s a mailtrap documentation.

It has not just been merged to production yet. You can check for it in the
staging branch

**Comment by Ayaan49** [comment]
Yes, there is one. I just checked it. Sorry for the confusion. Is there any SMS provider documentation I could work on? I enjoy writing that documentation. @unicodeveloper
