### ISSUE TITLE
Docs: Inconsistent size of headings

### ISSUE THREAD

**Issue by NXKED** [novuhq/docs#301]
Constantly changing between heading sizes in various documents in Client-Side and Server-Side Quickstart.
e.g. React has 'Requirements' and all following headings at the same size (h2). "React" and all other Framework names are h1 consecutively.

Client-Side/Angular has just all headings the same size.

I know there might be the idea to emphasize certain headings but for consistency, certain recurring headings like "Requirements" 
should have the same size.

---

<img src="https://github.com/novuhq/docs/assets/107938013/12da857e-51e0-4935-8d57-ab2693a777ca" width="470" height="400" />
<img src="https://github.com/novuhq/docs/assets/107938013/9f704bc4-d63e-4851-a28d-7911e693fb95" width="470" height="400" />
<img src="https://github.com/novuhq/docs/assets/107938013/be6163b0-57a8-477a-9bad-9366d459e348" width="470" height="400" />

**Comment by meekhasaji** [comment]
Hi
Please find some changes to resolve the inconsistency of heading sizes for some of the documents ( Vue, RedwoodJS).
Issue https://github.com/novuhq/docs/issues/301
PR link: https://github.com/novuhq/docs/pull/310

Thanks

**Comment by shawakash** [comment]
@Cliftonz Please Assign this to me.
