### ISSUE TITLE
Inconsistency and typo in Novu on windows docs

### ISSUE THREAD

**Issue by Solomon40** [novuhq/docs#303]
The [official documentation README](https://github.com/novuhq/docs) says to have Node v18 or higher
![image](https://github.com/novuhq/docs/assets/54350721/613504bb-f233-4045-8b6c-c7bed336eb07)
The [recently committed Novu on windows documentation](https://github.com/novuhq/docs/commit/62180f35c5a585362f24ac874a41fde69a426cb8) says Novu requires Node v16
![image](https://github.com/novuhq/docs/assets/54350721/0120b36a-30f2-490a-8d41-b08c79fa66c3)

Also, Ubuntu is the [default distro installed by WSL](https://learn.microsoft.com/en-us/windows/wsl/install)
![image](https://github.com/novuhq/docs/assets/54350721/efe35e94-ad7f-470b-82d3-54fa146be130)
rather than Debian as documented 
![image](https://github.com/novuhq/docs/assets/54350721/466893e4-45da-4436-9326-350a92a68a1a)

Would love to fix these ASAP

**Comment by Nitinshukla88** [comment]
Please assign this issue to me @Cliftonz

**Comment by sumitsaurabh927** [comment]
Any update here @Nitinshukla88 ?
