### ISSUE TITLE
 Docs Feedback: Space missing #4685

### ISSUE THREAD

**Issue by shawakash** [novuhq/docs#307]
Duplicates
 I have searched the existing issues
Related page
https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider

Kind of issue
Broken demonstration

Issue description
I was looking for the docs on adding new providers and it appears that a space is missing which is making it look bad.

Context 🔦
Add the space between 'infobipsupports' to make it 'infobi supports' .

![Example Image](https://user-images.githubusercontent.com/53791140/278771944-80350ad0-0383-4a01-8106-3c956cc56699.png)

Issue in novu codebase https://github.com/novuhq/novu/issues/4685

I am raising a Pr

**Comment by shawakash** [comment]
@rifont please review it

**Comment by Nitinshukla88** [comment]
@Cliftonz Please assign this issue to me.I want to work on it and if possible add hacktoberfest labael to it.

**Comment by Nitinshukla88** [comment]
Please add hacktoberfest label. @Cliftonz

**Comment by shawakash** [comment]
@Cliftonz i have raised a pr for this issue. If you could review it
