### ISSUE TITLE
Node.js code in create-subscriber.mdx has syntax issues

### ISSUE THREAD

**Issue by codingis4noobs2** [novuhq/docs#311]
File location: api-reference/subscribers/create-subscriber.mdx
The js code inside the file has syntax issues

Suggested changes: Fix syntax issues

**Comment by codingis4noobs2** [comment]
I would like to work on this issue

**Comment by jainpawan21** [comment]
@codingis4noobs2 

Fixe corresponding methods in this readme file as well
https://github.com/novuhq/novu/tree/next/packages/node#subscribers

**Comment by codingis4noobs2** [comment]
> @codingis4noobs2
> 
> Fixe corresponding methods in this section as well https://github.com/novuhq/novu/tree/next/packages/node#subscribers

Yeah sure

**Comment by codingis4noobs2** [comment]
@jainpawan21 Can you look

**Comment by codingis4noobs2** [comment]
Also it will be helpful if you could add hacktoberfest tag
