### ISSUE TITLE
Broken link for quickstart for python in python sdk 

### ISSUE THREAD

**Issue by Atharva1723** [novuhq/docs#335]
The link for python quickstart in the docs / sdks / python.mdx is not working for me 
https://docs.novu.co/sdks/python - > Python quickstart

System Details:-
Browser: Chrome 
Version: Version 118.0.5993.120
OS ; Windows 10

![image](https://github.com/novuhq/docs/assets/87201444/24a18740-1949-4b69-92db-3a5fafbdf59d)

![image](https://github.com/novuhq/docs/assets/87201444/93d36031-c55e-45bb-96b0-df532d65a7ee)

**Comment by unicodeveloper** [comment]
Assigned to you. Looking forward to your PR @Atharva1723
