### ISSUE TITLE
Redwood.js in the quickstart not rendering

### ISSUE THREAD

**Issue by Atharva1723** [novuhq/docs#337]
The Redwood js quickstart mdx file is not rendering in my browser :
System Details:-
Browser: Chrome
Version: Version 118.0.5993.120
OS ; Windows 10

You can also test it ... 

![image](https://github.com/novuhq/docs/assets/87201444/147a08a4-548a-43d9-8ace-47ff74f4e84a)

**Comment by unicodeveloper** [comment]
You have been assigned
