### ISSUE TITLE
Create a Nodemailer provider documentation page

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/docs#358]
Why?

To help our users easily integrate the delivery provider to Novu, we can create a dedicated page for each provider with instructions on how to: Get An API Key, create necessary adjustments and configurations on the provider side, and connect it to Novu.

How? 

You can look at the [SendGrid](https://docs.novu.co/channels/email/sendgrid) and [Slack](https://docs.novu.co/channels/chat/slack) examples on how to structure the page and content ideas.

**Comment by jainpawan21** [comment]
Closing this issue as we have custom SMTP documentation 
https://docs.novu.co/channels-and-providers/email/custom-smtp
