### ISSUE TITLE
📚 Docs Feedback: spelling mistake

### ISSUE THREAD

**Issue by Mutai-Gilbert** [novuhq/docs#378]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://docs.novu.co/getting-started/concepts

### Kind of issue

Other

### Issue description

I was reading the documentation and I encountered a spelling mistake.

### Context 🔦

I'll love to help in correcting the documentation.

**Comment by Mutai-Gilbert** [comment]
Hello, Kindly assign me the issue.

Thank you in advance.

**Comment by jainpawan21** [comment]
hi @Mutai-Gilbert 

I am transferring this issue to our docs repo

**Comment by Mutai-Gilbert** [comment]
Hello @jainpawan21 

This is the spelling mistake "communitication-context " under the channel header.

The link to the docs: https://docs.novu.co/getting-started/concepts

**Comment by unicodeveloper** [comment]
@Mutai-Gilbert Have you submitted a PR to this effect?
