### ISSUE TITLE
how to host it on AWS ec2

### ISSUE THREAD

**Issue by sai-aluru** [novuhq/docs#482]
Path: /self-hosting-novu/introduction
I am facing a network error when i am trying to sign up in my self hosted novu application on aws ec2. Can anyone help me out on this
![Uploading Screenshot 2024-01-18 at 11.20.04.png…]()

**Comment by unicodeveloper** [comment]
Please can you join the [Novu community on Discord](https://discord.gg/novu) and ask this question on the support channel @sai-aluru

**Comment by sai-aluru** [comment]
Thank you for your response
Regards
*Gnana Sai*

Devops Engineer

*www.hiringhood.com <http://www.hiringhood.com/>*

*M:* +91 8247373043
[image: image.png]

**Comment by jainpawan21** [comment]
@sai-aluru 

We recently added a video guide on how to host Novu on EC2.
https://www.loom.com/share/3af13939bfa54076a63c6360b7edaa19
