### ISSUE TITLE
Issue on docs - identifier vs. layoutId

### ISSUE THREAD

**Issue by typytypytypy** [novuhq/docs#518]
Path: /api-reference/layouts/update-a-layout

It's not clear what the difference is between the layoutId and the identifier, when updating a layout. Should I use the same string for both?  Is this something that is seen in the UI?

**Comment by unicodeveloper** [comment]
They are not the same.

The layoutId is the Novu system generated ID.

While the identifier is the user custom key you assign to a layout @typytypytypy
