### ISSUE TITLE
Issue on docs: missing Pushpad provider

### ISSUE THREAD

**Issue by collimarco** [novuhq/docs#522]
Path: /additional-resources/glossary

Hello,

On that page the Pushpad provider (https://docs.novu.co/channels-and-providers/push/pushpad) is missing. 

I hope that you can add it asap.

We have been featuring Novu on our blog (https://pushpad.xyz/blog) for several months, and is really sad to see that you haven't included Pushpad in your list.

Let me know

**Comment by unicodeveloper** [comment]
Hi @collimarco,

Please can you clarify what you mean by the pushpad provider is missing?

Here, in the list of push providers, we have Pushpad listed: https://docs.novu.co/channels-and-providers/push/overview

Here is a dedicated page to show how to connect to pushpad and trigger notification using Novu https://docs.novu.co/channels-and-providers/push/pushpad

So, can you point me to where pushpad is missng?

**Comment by collimarco** [comment]
> are you talking about here?

@unicodeveloper Yes, exactly :) I found that page because you linked to it in your recent newsletter and I didn't see Pushpad listed in the Push providers...

**Comment by unicodeveloper** [comment]
We'll update it now. This page is lagging behind on a lot of new channel providers across push, email and sms. @collimarco

**Comment by unicodeveloper** [comment]
@collimarco Please check again. We have updated it. It's live now.

**Comment by collimarco** [comment]
@unicodeveloper Great, thanks for the quick response!
